import Header from "@/app/_components/layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const globalSWRConfig = {
  revalidateOnFocus: false, // 다른 탭에서 돌아올 때마다 fetch를 비활성화
  // 다른 SWR 설정 옵션들도 필요한 경우 추가
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-slate-100 w-full min-h-screen p-10 ">
          <div className="md:container md:mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
