name: deploy
on:
  push:
    branches: ['deploy']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: 3.39.44.40
          username: ec2-user
          key: ${{ secrets.HUMANX_KEY }}
          script: |
            whoami
