name: deploy
on:
  push:
    branches: ['deploy']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.REMOTE_SSH_HOST }}
          username: ${{ vars.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.HUMANX_KEY }}
          passphrase: ${{ vars.REMOTE_SSH_PASSPHRASE }}
          port: ${{ vars.REMOTE_SSH_PORT }}
          script: |
            whoami
